### ISSUE TITLE
Items in Barrels are vanishing

### ISSUE THREAD

**Issue by Diverscope** [FTBTeam/FTB-Presents-Stoneblock-2#317] opened 2019-02-10 15:21 UTC
* **Modpack Version**: 1.4.0

* **Issue**: The description is a bit long, so I put it at the very end.

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: At least for me

* **Mod/s Affected**: Applied Energistics 2 rv6 Stable 6, Yabba 1.1.2.39, Draconic Evolution 2.3.18.329

* **Known Fix**: None

First: Sorry if this is the wrong Place. I know it's not a bug specific to Stoneblock 2, but I don't know the best Place to report this issue.

This bug has been bothering me for a long time. I set up an Applied Energistics system and connected four barrels with an "Infinity Upgrade" to the system via a storage bus (with priority +1). The channels neceassary for this are also enough. I store several items in the system and the system also tells me that all items have been successfully imported. However, when I close the save and restart it, all or almost all items suddenly has disappeared. They're not just invisible, they're completely gone. They are neither displayed in the system nor in the barrels. They also don't reappear when I break the barrels or interact with them in other way.

Example: I create a barrel for Cobblestone. First there are only 5 Cobblestone. After reloading the save, they are still there. Then I import the remaining Cobblestone via "Import Bus". The system now contains 252k Cobblestone in total (All saves in the barrel). I close the world and open it again - but now there are only 1732 Cobblestone left in the system. Since the Drawer (From where I imported the Cobblestone) is empty, the process of importing was still complete.

This also happens with other items. After a restart there are either completely or to some extent gone.

The AE system consists of several ME controllers. These are located in the Mining Dimension. The whole thing is chunkloaded. The terminal is located in the Overworld and is connected to the system.

Normally one could assume that this is a bug of the modpack, but I already had this phenomenon with FTB Beyond and Stoneblock 1. But with FTB Beyond this bug came only after I started a new save after a break of months.

Strangely enough, this bug doesn't happen when I use a drawer from the "Storage Drawer" mod. Items that I store in the "ME Drives" are also always maintained.

Stoneblock 2 was modified by me, but I only changed the minimap mod (Xaeros Minimap 1.16 -> Journeymap 5.5.3). but I don't think that this is related to the bug.

Things I've already tried:
- The items were inserted into the system by another method (e.g. manually by hand).
- Tried out other items
- Used barrels without the "Infinity Upgrade"
- Changed the priority of the "Storage Bus
- The AE system completely set up in the Overworld
- Moved the entire FTB folder from the secondary disk to the primary disk on my PC (because the secondary disk often causes problems, I thought that's the reason)
- Using "Quantum Storage" instead of barrels. However, this only led to more bugs.
- Filtering the "Storage Bus" so that it only accepts a certain item
- Removed the additional Java arguments I had used for FTB Beyond at the time to improve overall performance
- Windows has been reinstalled.

Another phenomenon that could be associated with this bug: If I build a multiblock-battery of "Draconic Evolution" and fill this with energy, then the latest energy level is not always taken over during saving. When I reopen the save, the battery level is lower than it was when I left the game. But this is not always the case.

Again I'm sorry if this is the wrong place. I don't know what to do with this bug, because it doesn't seem to be an explicit bug of any mod or modpack itself. I searched Google, but couldn't find a solution to my problem. I'm also sorry about the length of the text, but I wanted to add as much information as possible.

As you can (maybe) tell, I'm very desperate.

**Comment by LatvianModder** [comment] 2019-02-13 00:29
Your draconic evolution bug has been fixed. That happens when core is the only updating block in chunk, it previously didnt get marked for saving. I will look into yabba bug though removing arguments and reinstalling windows is bit too extreme <.<

**Comment by Sunekaer** [comment] 2019-02-25 13:29
Closing issue, Latvian is working on a solution

**Closed by Sunekaer** 2019-02-25 13:29 UTC

**Comment by LatvianModder** [comment] 2019-02-25 14:32
I couldn't reproduce this issue. Maybe just use drawers
